### ISSUE TITLE
Index page not showing Table of Contents

### ISSUE THREAD

**Issue by kylebarron** [r-spark/the-r-in-spark#2]
For some reason, the table of contents isn't showing correctly on your index page.

Chromium:
![image](https://user-images.githubusercontent.com/15164633/47666035-fce19200-db78-11e8-9354-14943ab01fd2.png)

Firefox:
![image](https://user-images.githubusercontent.com/15164633/47666022-f3582a00-db78-11e8-81f3-c3373ebcbb12.png)

If I manually go to a different page on the site, the Table of Contents does appear:
![image](https://user-images.githubusercontent.com/15164633/47666113-24385f00-db79-11e8-9944-c832e420683c.png)

I haven't worked with Gitbook before so I'm not sure what the error is.

**Comment by kylebarron** [comment]
Are you intentionally preventing this from showing?
https://github.com/javierluraschi/the-r-in-spark/blob/93798fa9f93b9ad7abe1a7252f03c26653a006ed/index.Rmd#L20-L30

**Comment by javierluraschi** [comment]
@kylebarron yes, it's being hidden, we got asked by the publisher to hide the contents until the book gets written/published, give it ~6 months. This book will still be available online, but it won't be easily accessible while is being written.

How are you planning to use this content? Do you have feedback? Would love to understand this more to make sure we address this while writing this content.

**Comment by kylebarron** [comment]
That's fine. I was just confused.

I'm working to get a Spark cluster installed for myself and other economics researchers who work with large health data. Since many have at least some knowledge of R, I'd been thinking that the Sparklyr interface would be the best way to promote use of Spark. I don't really have feedback yet, but when finished the book looks like it would be a good resource to recommend to people.

**Comment by javierluraschi** [comment]
@kylebarron great and thank you! You know how to get access to this content, so feel free to send feedback our way. In fact, if you can think of topics you would like us to cover, feel free to open GitHub issues to make sure we, at least the very least, consider them. Cheers!
