### ISSUE TITLE
Distrubuted R: Add a Guideline for New Bee

### ISSUE THREAD

**Issue by harryprince** [r-spark/the-r-in-spark#30]
Most of the new `sparklyr` users pass local R code directly to `spark_apply` function failed, due to the spark memory management problem.

such as `dplyr::mutate` function copy memory.

**Comment by javierluraschi** [comment]
@harryprince do you have a reproducible example? Either, we can try to fix in `sparklyr` or make an appropriate note ion the book.

**Comment by harryprince** [comment]
@javierluraschi yes, I got some examples, I will finish that job in the near future.

**Comment by javierluraschi** [comment]
@harryprince we are actually locking down the book next week, so it's now or.... until the second edition :)

**Comment by javierluraschi** [comment]
Closing, we can reconsider in second edition.
