### ISSUE TITLE
Java install instructions out-of-date

### ISSUE THREAD

**Issue by alexkgold** [r-spark/the-r-in-spark#40]
Was just talking to @edgararuiz about this -- love the book. Went from nothing to sparklyr-ing really quickly. Only issue is that the Java installation instructions weren't quite right.

For example, link in the appendix leads to installer for the newest plugin, not the JDK.

I wrote up detailed instructions for OSX for [support website](https://support.rstudio.com/hc/en-us/articles/360023225693). Probably not the level of detail you want in book, but may want to take the link to actual JDK downloads: https://www.oracle.com/technetwork/java/javase/downloads/index.html

**Comment by javierluraschi** [comment]
We don't need the JDK, JRE is sufficient. Except for the Contributing chapter which does require compiling Java code and the JDK8, I'll add a note to switch to the JDK in that chapter.
