### ISSUE TITLE
Pipelines: Find home for "Analysis versus Production work"

### ISSUE THREAD

**Issue by edgararuiz-zz** [r-spark/the-r-in-spark#41]
## Analysis versus Production work

The main "deliverable" of data analysis project is the answer to a question. The answer is encased in one or several data transformations, visualizations or models. Putting the transformations, visualizations or models into an automated process that delivers continuous insights should be considered a Production project.  Analysis and Production should be considered as separate projects. Specifically to R, Production projects would involve creating a `shiny` app that folks in the organization depend on, and is used on a daily basis.  Another example of an Production artifact, is a scheduled R script reads and updates the data store with new scores. 

From the Information Technology perspective.  The nature of the analysis project is experimental, the resulting code does not need to be tested or promoted as is to a Production system.  In contrast, the Production project needs to pass the usual Software Development Lifecyle (SDLC) requirements before it is ready to be placed as part of the supported reports or applications withing the organization.

```{r echo=FALSE, fig.cap='Analysis vs Production projects', fig.align = 'center', eval = eval_code}
render_nomnoml("
#direction: right
#edgeMargin: 2
#padding: 10
#fontSize: 12

[Analysis Project |
  [Analyze] -> [Communicate]] -> [Production Project | 
    [Develop R script] -> [Test script]
    [Test script] -> [Approve to run on a daily basis]] 
[Production Project] -> [Production]
[<note>e.g: Identify risk factors and build scores]-/-[<note> e.g: Score customers on a daily basis]
", "images/analysis-program.png")
```

**Comment by javierluraschi** [comment]
I think this would go into pipelines... Kevin might already have something around these lines.

**Comment by edgararuiz-zz** [comment]
That makes perfect sense, thanks

**Comment by javierluraschi** [comment]
Unless Kevin wants to add something... closing.
