### ISSUE TITLE
H2O rsparkling review

### ISSUE THREAD

**Issue by navdeep-G** [r-spark/the-r-in-spark#50]
* Some comments so far:
    - I am not sure if you can save h2o models this way: https://github.com/javierluraschi/the-r-in-spark/blob/master/extensions.Rmd#L152. Maybe better to follow this: http://docs.h2o.ai/h2o/latest-stable/h2o-docs/save-and-load-model.html
    - Any reason why the dataset used is so small? (32 rows)
    - Add a line of code to automl to show how to grab the leader model and carry out some actions with it (make predictions or look at parameters)
    - Link directly to the AutoML user guide in the text here: https://github.com/javierluraschi/the-r-in-spark/blob/master/extensions.Rmd#L188

@ledell @javierluraschi

**Comment by ledell** [comment]
Additional info for @navdeep-G's comments:

> - I am not sure if you can save h2o models this way: https://github.com/javierluraschi/the-r-in-spark/blob/master/extensions.Rmd#L152

To save/load H2O models to disk, you must use [`h2o.saveModel()`](http://docs.h2o.ai/h2o/latest-stable/h2o-r/docs/reference/h2o.saveModel.html) and [`h2o.loadModel()`](http://docs.h2o.ai/h2o/latest-stable/h2o-r/docs/reference/h2o.loadModel.html).

> - Add a line of code to automl to show how to grab the leader model and carry out some actions with it (make predictions or look at parameters)
```
leader <- automl@leader  #leader model stored here
h2o.predict(leader, test)  #generate predictions on a test set
leader@parameters  #look at leader model hyperparameters
```

> - Link directly to the AutoML user guide in the text here:

Here's the page to link to: http://docs.h2o.ai/h2o/latest-stable/h2o-docs/automl.html

**Comment by javierluraschi** [comment]
Thank you so much, feedback addressed, see: https://therinspark.com/extensions.html#h2o
