### ISSUE TITLE
Book's Sidebar Only Available For Two Chapters

### ISSUE THREAD

**Issue by gfleetwood** [r-spark/the-r-in-spark#82]
I can only see the book's sidebar for chapters 14 and 15. It can't be accessed for the others.

**Comment by Triamus** [comment]
I cannot access the side bar for any chapter (in only appears very shortly on initial page load). Tried in chrome and edge. Also the next/previous page navigation arrows are gone. Interestingly everything is there when accessing https://therinspark.com/introduction.html.
